#!/usr/bin/env php
<?php
require_once __DIR__.'/../vendor/autoload.php'; 

use upload\command\DemoCommand;
use upload\command\ContableCommand;
use upload\command\EmpleadosCommand;
use upload\command\DocumentCommand;
use upload\command\GetDocumentsCommand;
use upload\command\ClientsCartagenaCommand;
use upload\command\InmueblesCartagenaCommand;
use upload\command\FotosInmueblesCartagenaCommand;
use upload\command\ConveniosCartagenaCommand;
use upload\command\ContratoArriendoCommand;
use upload\command\ComentariosInmuebleCommand;
use upload\command\UpdateInmuebleCommand;
use upload\command\UpdateClientesCommand;

use Knp\Provider\ConsoleServiceProvider;


$app = new Silex\Application();



$app->register(new ConsoleServiceProvider(), array(
    'console.name'              => 'MyApplication',
    'console.version'           => '1.0.0',
    'console.project_directory' => __DIR__.'/..'
));



$app->register(new ConsoleServiceProvider(),
                array('console.name'              => 'Console',
                      'console.version'           => '1.0.0',
                      'console.project_directory' => __DIR__.'/..'));
$console = $app['console'];

// agregar commandos
$console->add(new DemoCommand());
$console->add(new EmpleadosCommand());
$console->add(new ContableCommand());
$console->add(new DocumentCommand());
$console->add(new GetDocumentsCommand());
$console->add(new ClientsCartagenaCommand());
$console->add(new InmueblesCartagenaCommand());
$console->add(new FotosInmueblesCartagenaCommand());
$console->add(new ConveniosCartagenaCommand());
$console->add(new ContratoArriendoCommand());
$console->add(new ComentariosInmuebleCommand());
$console->add(new UpdateInmuebleCommand());
$console->add(new UpdateClientesCommand());

$console->run();



