#!/usr/bin/env php
<?php
require_once __DIR__.'/../vendor/autoload.php'; 

use upload\command\DemoCommand;
use upload\command\ContableCommand;
use upload\command\EmpleadosCommand;
use upload\command\DocumentCommand;
use upload\command\GetDocumentsCommand;
use upload\command\ClientsCartagenaCommand;
use upload\command\InmueblesCartagenaCommand;
use upload\command\FotosInmueblesCartagenaCommand;
use upload\command\ConveniosCartagenaCommand;
use upload\command\ComentariosInmuebleCommand;
use upload\command\UpdateInmuebleCommand;
use upload\command\UpdateInmueblesRCommand;
use upload\command\UpdateClientesCommand;
use upload\command\ContratosDeMandatoCommand;
use upload\command\OportunityCommand;
use upload\command\ContratoArriendoCommand;
use upload\command\PropietariosCommand;
use upload\command\ErrorInmuebleMongoCommand;
use upload\command\ErrorAgreementCommand;
use upload\command\PublicarInmuebleCommand;
use upload\command\ArrendatariosCommand;
use upload\command\ComentariosContratoArriendoCommand;
use upload\command\TiposDeDocumentosCommand;
use upload\command\UpdateContratoArriendoCommand;
use upload\command\UpdateConveniosCommand;
use upload\command\UpdateMandateContractCommand;
use upload\command\MapperCommand;
use upload\command\VentaUsadosCommand;
use upload\command\AvaluosCommand;
use upload\command\Cartagena\UpdateInmuebleDayCommand;

use upload\command\ClientsMonteriaCommand;
use upload\command\InmueblesMonteriaCommand;
use upload\command\FotosInmueblesMonteriaCommand;
use upload\command\ConveniosMonteriaCommand;
use upload\command\ComentariosInmuebleMonteriaCommand;
use upload\command\UpdateInmuebleMonteriaCommand;
use upload\command\UpdateInmueblesRMonteriaCommand;
use upload\command\UpdateClientesMonteriaCommand;
use upload\command\ContratosDeMandatoMonteriaCommand;
use upload\command\OportunityMonteriaCommand;
use upload\command\ContratoArriendoMonteriaCommand;
use upload\command\PropietariosMonteriaCommand;
use upload\command\ErrorInmuebleMongoMonteriaCommand;
use upload\command\ErrorAgreementMonteriaCommand;
use upload\command\PublicarInmuebleMonteriaCommand;
use upload\command\ArrendatariosMonteriaCommand;
use upload\command\ComentariosContratoArriendoMonteriaCommand;
use upload\command\TiposDeDocumentosMonteriaCommand;
use upload\command\ErrorClientMonteriaCommand;

use upload\command\Bogota\MapperBogotaCommand;
use upload\command\Bogota\ClientsBogotaCommand;

use Knp\Provider\ConsoleServiceProvider;


$app = new Silex\Application();



$app->register(new ConsoleServiceProvider(), array(
    'console.name'              => 'MyApplication',
    'console.version'           => '1.0.0',
    'console.project_directory' => __DIR__.'/..'
));



$app->register(new ConsoleServiceProvider(),
                array('console.name'              => 'Console',
                      'console.version'           => '1.0.0',
                      'console.project_directory' => __DIR__.'/..'));
$console = $app['console'];

// agregar commandos
$console->add(new DemoCommand());
$console->add(new EmpleadosCommand());
$console->add(new ContableCommand());
$console->add(new DocumentCommand());
$console->add(new GetDocumentsCommand());
$console->add(new ClientsCartagenaCommand());
$console->add(new InmueblesCartagenaCommand());
$console->add(new FotosInmueblesCartagenaCommand());
$console->add(new ConveniosCartagenaCommand());
$console->add(new ComentariosInmuebleCommand());
$console->add(new UpdateInmuebleCommand());
$console->add(new UpdateInmueblesRCommand());
$console->add(new UpdateClientesCommand());
$console->add(new ContratosDeMandatoCommand());
$console->add(new OportunityCommand());
$console->add(new ContratoArriendoCommand());
$console->add(new PropietariosCommand());
$console->add(new ErrorInmuebleMongoCommand());
$console->add(new ErrorAgreementCommand());
$console->add(new PublicarInmuebleCommand());
$console->add(new ArrendatariosCommand());
$console->add(new ComentariosContratoArriendoCommand());
$console->add(new TiposDeDocumentosCommand());
$console->add(new UpdateContratoArriendoCommand());
$console->add(new UpdateConveniosCommand());
$console->add(new UpdateMandateContractCommand());
$console->add(new MapperCommand());
$console->add(new VentaUsadosCommand());
$console->add(new AvaluosCommand());
$console->add(new UpdateInmuebleDayCommand());

$console->add(new ClientsMonteriaCommand());
$console->add(new InmueblesMonteriaCommand());
$console->add(new FotosInmueblesMonteriaCommand());
$console->add(new ConveniosMonteriaCommand());
$console->add(new ComentariosInmuebleMonteriaCommand());
$console->add(new UpdateInmuebleMonteriaCommand());
$console->add(new UpdateInmueblesRMonteriaCommand());
$console->add(new UpdateClientesMonteriaCommand());
$console->add(new ContratosDeMandatoMonteriaCommand());
$console->add(new OportunityMonteriaCommand());
$console->add(new ContratoArriendoMonteriaCommand());
$console->add(new PropietariosMonteriaCommand());
$console->add(new ErrorInmuebleMongoMonteriaCommand());
$console->add(new ErrorAgreementMonteriaCommand());
$console->add(new PublicarInmuebleMonteriaCommand());
$console->add(new ArrendatariosMonteriaCommand());
$console->add(new ComentariosContratoArriendoMonteriaCommand());
$console->add(new TiposDeDocumentosMonteriaCommand());
$console->add(new ErrorClientMonteriaCommand());

$console->add(new MapperBogotaCommand());
$console->add(new ClientsBogotaCommand());

$console->run();



